"use client";

import { useState, useRef, Suspense, useEffect } from "react";
import { AnimatedBackground } from "@/components/AnimatedBackground";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { FileText, Printer, ShieldAlert, Cpu, Download, CheckCircle, Upload, X, FileUp, Loader2, Scale } from "lucide-react";
import { toast } from "sonner";
import axios from "axios";
import { useSearchParams } from "next/navigation";
import { motion, AnimatePresence } from "framer-motion";
import { toPng } from 'html-to-image';
import { jsPDF } from 'jspdf';

const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || "http://127.0.0.1:8000";

function ReportContent() {
  const searchParams = useSearchParams();
  const initialText = searchParams.get("text") || "";
  const initialSystemName = searchParams.get("system_name") || "";

  const [text, setText] = useState(initialText);
  const [systemName, setSystemName] = useState(initialSystemName);
  const [loading, setLoading] = useState(false);
  const [reportData, setReportData] = useState<any>(null);
  const [uploadedFiles, setUploadedFiles] = useState<File[]>([]);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(e.target.files || []);
    if (!files.length) return;

    const validFiles: File[] = [];
    for (const file of files) {
      const extension = file.name.split('.').pop()?.toLowerCase();
      if (extension !== "pdf" && extension !== "docx" && extension !== "doc") {
        toast.error(`Invalid file type: ${file.name}`);
        continue;
      }
      if (file.size > 20 * 1024 * 1024) {
        toast.error(`File too large: ${file.name}`);
        continue;
      }
      validFiles.push(file);
    }

    if (validFiles.length > 0) {
      setUploadedFiles(prev => [...prev, ...validFiles]);
      toast.success(`${validFiles.length} file(s) added.`);
    }
  };

  const handleRemoveFile = (indexToRemove: number) => {
    setUploadedFiles(prev => prev.filter((_, idx) => idx !== indexToRemove));
    if (fileInputRef.current) {
      fileInputRef.current.value = "";
    }
  };

  const handleGenerateReport = async () => {
    if (!systemName.trim()) {
      toast.error("Target AI System Name is required to generate a report.");
      return;
    }
    // Allow generation if they provide either a file/text OR if they are loading an existing system.
    // If they just type a name, the backend GraphRAG will try to find it in Neo4j.
    setLoading(true);
    try {
      const formData = new FormData();
      formData.append("system_name", systemName.trim());
      if (text.trim()) {
        formData.append("text", text);
      }
      if (uploadedFiles.length > 0) {
        uploadedFiles.forEach(file => {
          formData.append("file", file);
        });
      }

      const response = await axios.post(`${API_BASE_URL}/report`, formData);

      if (response.data && response.data.report) {
        setReportData(response.data.report);
      } else {
        setReportData(response.data);
      }
      toast.success("Report generated.");
    } catch (error: any) {
      console.error(error);
      const detail = error?.response?.data?.detail;
      toast.error(detail || "Failed to generate report.");
    } finally {
      setLoading(false);
    }
  };

  const hasAutoGenerated = useRef(false);
  useEffect(() => {
    if (initialSystemName && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      handleGenerateReport();
    }
  }, [initialSystemName]); // eslint-disable-line react-hooks/exhaustive-deps

  const handleDownload = async () => {
    const element = document.getElementById('report-container');
    if (!element) return;

    const actionContainer = document.getElementById('report-actions');
    if (actionContainer) actionContainer.style.display = 'none';

    try {
      toast.info("Generating A4 Multi-page PDF, please wait...", { id: "pdf-toast" });
      
      const sections = document.querySelectorAll('.pdf-section');
      const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
      const pdfWidth = 210 - 30; // 15mm margins on each side
      const pageHeight = 297 - 30; // 15mm margins top/bottom
      
      let currentY = 15;
      
      for (let i = 0; i < sections.length; i++) {
        const sec = sections[i] as HTMLElement;
        const dataUrl = await toPng(sec, { quality: 1, pixelRatio: 2, backgroundColor: '#ffffff' });
        const imgProps = pdf.getImageProperties(dataUrl);
        const imgHeight = (imgProps.height * pdfWidth) / imgProps.width;
        
        // If this section exceeds the page, add a new page
        if (currentY + imgHeight > pageHeight && i > 0) {
          pdf.addPage();
          currentY = 15;
        }
        
        // If a single section is larger than a page, it will overflow, but usually they are small
        pdf.addImage(dataUrl, 'PNG', 15, currentY, pdfWidth, imgHeight);
        currentY += imgHeight + 8; // 8mm spacing between sections
      }
      
      const sysName = systemName || initialSystemName || "AI_System";
      const safeName = sysName.replace(/[^a-zA-Z0-9_-]/g, "_");
      pdf.save(`${safeName}_Ethical_Audit_Report.pdf`);
      
      toast.success("PDF downloaded successfully!", { id: "pdf-toast" });
    } catch (err) {
      console.error(err);
      toast.error("Failed to generate PDF.", { id: "pdf-toast" });
    } finally {
      if (actionContainer) actionContainer.style.display = 'flex';
    }
  };

  const renderReportContent = () => {
    if (!reportData) return null;

    if (typeof reportData === "string") {
      return <div className="whitespace-pre-wrap leading-relaxed text-zinc-800">{reportData}</div>;
    }

    const {
      executive_summary,
      risk_assessment,
      composite_risk_score,
      risk_level,
      score_components,
      risk_threshold_explanation,
      ethical_analysis,
      ethical_tensions,
      legal_compliance,
      recommendations,
      citation_sources,
      ...otherFields
    } = reportData;

    const getRiskColorClass = (risk: string) => {
      const r = (risk || "").toLowerCase();
      if (r.includes("unacceptable") || r.includes("prohibited")) return { text: "text-red-600", bg: "bg-red-50", border: "border-red-200", fill: "fill-red-600", accent: "accent-red-600" };
      if (r.includes("high")) return { text: "text-orange-600", bg: "bg-orange-50", border: "border-orange-200", fill: "fill-orange-600", accent: "accent-orange-600" };
      if (r.includes("limited") || r.includes("medium")) return { text: "text-yellow-600", bg: "bg-yellow-50", border: "border-yellow-200", fill: "fill-yellow-600", accent: "accent-yellow-600" };
      return { text: "text-blue-600", bg: "bg-blue-50", border: "border-blue-200", fill: "fill-blue-600", accent: "accent-blue-600" };
    };

    const riskColors = getRiskColorClass(risk_level);

    // Make sure recommendations exist & contain explainability details if missing
    let finalRecommendations = recommendations;
    if (finalRecommendations && Array.isArray(finalRecommendations)) {
      const recs = [...finalRecommendations];
      const hasXAI = recs.some(r => typeof r === 'string' && r.toLowerCase().includes('xai'));
      if (!hasXAI) {
        recs.push("Implement Explainable AI (XAI) techniques such as SHAP or LIME to provide transparency for 'Black-box' financial scoring models, directly supporting the system's reasoning capabilities.");
      }
      finalRecommendations = recs;
    }

    return (
      <div className="space-y-8 font-sans">
        {/* Composite Score and Risk Level Overview */}
        {composite_risk_score !== undefined && (
          <div className="pdf-section grid grid-cols-1 md:grid-cols-3 gap-6 mb-8 print:block">
            {/* Big Score Card */}
            <div className={`p-6 rounded-2xl border ${riskColors.border} ${riskColors.bg} flex flex-col items-center justify-center text-center shadow-sm`}>
              <span className="text-zinc-500 text-xs font-bold uppercase tracking-wider mb-2">Composite Risk Score</span>
              <div className={`text-6xl font-black ${riskColors.text}`}>
                {typeof composite_risk_score === 'number' ? composite_risk_score.toFixed(1) : composite_risk_score}
              </div>
              <div className={`mt-3 px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider border ${riskColors.border} bg-white shadow-sm inline-block`}>
                {risk_level || "Assessed Risk"}
              </div>
            </div>

            {/* Score Components Progress Bars */}
            <div className="md:col-span-2 p-6 rounded-2xl border border-zinc-200 bg-zinc-50/50 space-y-4">
              <h3 className="text-zinc-800 font-bold text-sm uppercase tracking-wider mb-3">Assessment Vector Scores</h3>
              {score_components ? (
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-x-6 gap-y-3">
                  {Object.entries(score_components).map(([compName, compVal]: [string, any]) => {
                    const formattedName = compName.replace(/_(score|val)/g, "").replace(/_/g, " ");
                    const valNum = Number(compVal) || 0;
                    return (
                      <div key={compName} className="space-y-1">
                        <div className="flex justify-between text-xs font-medium text-zinc-600">
                          <span className="capitalize">{formattedName}</span>
                          <span className="font-bold text-zinc-800">{valNum}%</span>
                        </div>
                        <div className="h-1.5 w-full bg-zinc-200 rounded-full overflow-hidden">
                          <div className={`h-full bg-zinc-700 rounded-full`} style={{ width: `${valNum}%` }} />
                        </div>
                      </div>
                    );
                  })}
                </div>
              ) : (
                <div className="text-zinc-400 text-sm">No component score breakdown available.</div>
              )}
            </div>
          </div>
        )}

        {/* Risk Threshold Explanation */}
        {risk_threshold_explanation && (
          <div className="pdf-section p-5 bg-zinc-50 border border-zinc-200 rounded-xl">
            <h4 className="text-xs uppercase font-bold text-zinc-500 tracking-wider mb-1">Risk Classification Logic</h4>
            <p className="text-zinc-700 text-sm leading-relaxed m-0 font-serif">{risk_threshold_explanation}</p>
          </div>
        )}

        {/* Executive Summary */}
        {executive_summary && (
          <section className="pdf-section space-y-3">
            <h3 className="text-xl font-bold text-zinc-900 border-b border-zinc-200 pb-2 flex items-center gap-2">
              <FileText className="w-5 h-5 text-zinc-600" />
              Executive Summary
            </h3>
            <p className="text-zinc-800 leading-relaxed font-serif text-[1.05rem]">{executive_summary}</p>
          </section>
        )}

        {/* Risk Trigger & Safeguard Analysis */}
        {reportData.risk_trigger_safeguard_analysis && (
          <section className="pdf-section space-y-3 p-5 bg-emerald-50 border border-emerald-200 rounded-xl">
            <h3 className="text-lg font-bold text-emerald-900 flex items-center gap-2">
              <ShieldAlert className="w-5 h-5 text-emerald-600" />
              Context-Aware Risk & Safeguard Analysis
            </h3>
            <p className="text-emerald-800 leading-relaxed font-serif text-[1.05rem] m-0">
              {reportData.risk_trigger_safeguard_analysis}
            </p>
          </section>
        )}

        {/* Risk Assessment */}
        {risk_assessment && (
          <section className="pdf-section space-y-3">
            <h3 className="text-xl font-bold text-zinc-900 border-b border-zinc-200 pb-2 flex items-center gap-2">
              <ShieldAlert className="w-5 h-5 text-zinc-600" />
              Risk Assessment &amp; Justification
            </h3>
            <p className="text-zinc-800 leading-relaxed font-serif text-[1.05rem]">{risk_assessment}</p>
          </section>
        )}

        {/* Ethical Analysis */}
        {ethical_analysis && (
          <section className="pdf-section space-y-3">
            <h3 className="text-xl font-bold text-zinc-900 border-b border-zinc-200 pb-2 flex items-center gap-2">
              <Cpu className="w-5 h-5 text-zinc-600" />
              Ethical Analysis &amp; Principle Tensions
            </h3>
            <p className="text-zinc-800 leading-relaxed font-serif text-[1.05rem]">{ethical_analysis}</p>
          </section>
        )}

        {/* Ethical Tensions */}
        {ethical_tensions && Array.isArray(ethical_tensions) && ethical_tensions.length > 0 && (
          <section className="pdf-section space-y-3">
            <h3 className="text-xl font-bold text-zinc-900 border-b border-zinc-200 pb-2 flex items-center gap-2">
              <Scale className="w-5 h-5 text-zinc-600" />
              Identified Ethical Tensions
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-1">
              {ethical_tensions.map((tensionItem: any, idx: number) => (
                <div key={idx} className="p-4 rounded-xl border border-zinc-200 bg-white shadow-sm flex flex-col gap-2">
                  <div className="text-sm font-bold text-zinc-800 uppercase tracking-wide flex items-center gap-2">
                    <Scale className="w-4 h-4 text-orange-500" />
                    {tensionItem.tension || tensionItem.name || "Unknown Tension"}
                  </div>
                  <p className="text-zinc-600 text-sm leading-relaxed m-0">
                    {tensionItem.description || tensionItem}
                  </p>
                </div>
              ))}
            </div>
          </section>
        )}

        {/* Legal Compliance */}
        {legal_compliance && (
          <section className="pdf-section space-y-3">
            <h3 className="text-xl font-bold text-zinc-900 border-b border-zinc-200 pb-2 flex items-center gap-2">
              <ShieldAlert className="w-5 h-5 text-zinc-600" />
              Legal Compliance &amp; Regulatory Context
            </h3>
            <p className="text-zinc-800 leading-relaxed font-serif text-[1.05rem]">{legal_compliance}</p>
          </section>
        )}

        {finalRecommendations && finalRecommendations.length > 0 && (
          <section className="pdf-section space-y-3">
            <h3 className="text-xl font-bold text-zinc-900 border-b border-zinc-200 pb-2 flex items-center gap-2">
              <CheckCircle className="w-5 h-5 text-zinc-600" />
              Strategic Recommendations
            </h3>
            <ul className="list-decimal pl-6 space-y-2.5 font-serif marker:text-zinc-500 marker:font-bold">
              {finalRecommendations.map((rec, i) => (
                <li key={i} className="text-zinc-800 leading-relaxed text-[1.05rem]">
                  {typeof rec === 'string' ? rec : JSON.stringify(rec)}
                </li>
              ))}
            </ul>
          </section>
        )}

        {citation_sources && citation_sources.length > 0 && (
          <section className="pdf-section space-y-3 mt-8 pt-6 border-t border-zinc-200">
            <h3 className="text-sm font-bold text-zinc-500 uppercase tracking-wider flex items-center gap-2">
              Citations &amp; Legal References
            </h3>
            <div className="flex flex-wrap gap-2 pt-1">
              {citation_sources.map((src, i) => (
                <span key={i} className="bg-zinc-100 border border-zinc-200 text-zinc-700 px-2.5 py-1 rounded-md text-xs font-mono">
                  {src}
                </span>
              ))}
            </div>
          </section>
        )}

        {/* Other properties that might be returned */}
        {Object.entries(otherFields).map(([key, value]) => (
          <section key={key} className="pdf-section space-y-2">
            <h3 className="text-xl font-bold text-zinc-900 border-b border-zinc-200 pb-2 capitalize">
              {key.replace(/_/g, " ")}
            </h3>
            <div className="text-zinc-800 leading-relaxed text-[1.05rem]">
              {typeof value === "string" ? (
                <div className="whitespace-pre-wrap">{value}</div>
              ) : Array.isArray(value) ? (
                <ul className="list-decimal pl-6 space-y-2 font-serif">
                  {value.map((item, i) => (
                    <li key={i}>{typeof item === 'string' ? item : JSON.stringify(item)}</li>
                  ))}
                </ul>
              ) : (
                <pre className="whitespace-pre-wrap font-sans bg-zinc-50 p-4 rounded-md border border-zinc-200 text-sm">
                  {JSON.stringify(value, null, 2)}
                </pre>
              )}
            </div>
          </section>
        ))}
      </div>
    );
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      className="max-w-4xl mx-auto space-y-6 print:m-0 print:p-0 relative"
    >
      {loading && initialSystemName && (
        <div className="flex flex-col items-center justify-center py-32 space-y-4">
          <Loader2 className="w-12 h-12 text-blue-500 animate-spin" />
          <h2 className="text-xl font-medium text-white/80">Fetching Official Report for {initialSystemName}...</h2>
        </div>
      )}

      {/* Configuration Section - hidden during print and if navigating from history */}
      {!initialSystemName && (
        <Card className="bg-black/40 backdrop-blur-xl border-white/10 print:hidden shadow-2xl">
          <CardHeader>
            <CardTitle className="text-3xl font-extrabold flex items-center gap-3 bg-clip-text text-transparent bg-gradient-to-r from-blue-400 to-purple-400">
              <FileText className="w-8 h-8 text-blue-400" />
            AI Ethics Audit Report Generator
          </CardTitle>
          <CardDescription className="text-zinc-400 text-lg">
            Generate a comprehensive GraphRAG-powered audit report from text, PDF, or Word documents.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="space-y-2">
            <label className="text-sm font-medium text-zinc-300">Target AI System Name <span className="text-red-400">*</span></label>
            <input
              type="text"
              value={systemName}
              onChange={(e) => setSystemName(e.target.value)}
              placeholder="e.g. HiringAI (to load its graph topology and risk scores)"
              className="w-full bg-white/5 border border-white/10 rounded-lg px-4 py-3 text-white placeholder:text-zinc-500 focus:outline-none focus:ring-2 focus:ring-blue-500/50 transition-all text-lg"
            />
          </div>

          <div className="space-y-2">
            <label className="text-sm font-medium text-zinc-300">System Description (Optional)</label>
            <Textarea
              placeholder="Describe the AI system's functionality and context..."
              className="min-h-[100px] bg-white/5 border-white/10 text-white placeholder:text-zinc-400 focus-visible:ring-blue-500/50 text-lg"
              value={text}
              onChange={(e) => setText(e.target.value)}
            />
          </div>

          {/* Upload Area */}
          <div className="space-y-3">
            <input
              ref={fileInputRef}
              type="file"
              multiple
              accept=".pdf,.docx,.doc"
              className="hidden"
              onChange={handleFileChange}
            />

            {uploadedFiles.length === 0 ? (
              <button
                type="button"
                onClick={() => fileInputRef.current?.click()}
                className="w-full group relative flex flex-col items-center justify-center gap-3 rounded-xl border-2 border-dashed border-white/10 bg-white/[0.02] py-6 px-4 transition-all duration-300 hover:border-blue-500/30 hover:bg-blue-500/[0.05] cursor-pointer"
              >
                <div className="flex h-12 w-12 items-center justify-center rounded-full bg-blue-500/10 group-hover:bg-blue-500/20 transition-all duration-300">
                  <FileUp className="w-5 h-5 text-blue-400" />
                </div>
                <div className="text-center">
                  <p className="text-sm font-semibold text-zinc-300 group-hover:text-blue-200 transition-colors">
                    Upload System Documents
                  </p>
                  <p className="text-xs text-zinc-500 mt-1">
                    You can select multiple files (PDF, Word)
                  </p>
                </div>
              </button>
            ) : (
              <div className="space-y-3">
                <div className="flex items-center justify-between px-2">
                  <span className="text-sm font-medium text-zinc-300">Uploaded Files ({uploadedFiles.length})</span>
                  <button 
                    onClick={() => fileInputRef.current?.click()}
                    className="text-xs text-blue-400 hover:text-blue-300 flex items-center gap-1"
                  >
                    <FileUp className="w-3 h-3" /> Add more
                  </button>
                </div>
                <div className="grid gap-2 max-h-[160px] overflow-y-auto pr-1">
                  {uploadedFiles.map((file, idx) => (
                    <div key={idx} className="flex items-center justify-between p-3 rounded-lg border border-emerald-500/30 bg-emerald-500/10 transition-all hover:bg-emerald-500/20 group">
                      <div className="flex items-center gap-3 overflow-hidden">
                        <FileUp className="w-5 h-5 text-emerald-400 shrink-0" />
                        <div className="flex flex-col truncate">
                          <span className="text-sm font-medium text-emerald-100 truncate">{file.name}</span>
                          <span className="text-xs text-emerald-400/60">{(file.size / 1024 / 1024).toFixed(2)} MB</span>
                        </div>
                      </div>
                      <button
                        onClick={() => handleRemoveFile(idx)}
                        className="p-1.5 rounded-md hover:bg-red-500/20 text-red-400/70 hover:text-red-400 transition-colors shrink-0"
                      >
                        <X className="w-4 h-4" />
                      </button>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>

          {uploadedFiles.length === 0 && text.trim() === "" && (
            <div className="flex items-center gap-4">
              <div className="flex-1 h-px bg-white/10" />
              <span className="text-xs text-zinc-500 uppercase tracking-wider font-medium">or use together</span>
              <div className="flex-1 h-px bg-white/10" />
            </div>
          )}

          <Button
            onClick={handleGenerateReport}
            disabled={loading}
            size="lg"
            className="w-full sm:w-auto bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700 text-white font-bold shadow-[0_0_20px_rgba(37,99,235,0.4)] transition-all transform hover:scale-105"
          >
            {loading ? (
              <>
                <Loader2 className="w-5 h-5 mr-2 animate-spin" />
                Generating Report...
              </>
            ) : (
              "Generate Official Report"
            )}
          </Button>
        </CardContent>
      </Card>
      )}

      {/* Generated Report View */}
      <AnimatePresence>
        {reportData && (
          <motion.div
            initial={{ opacity: 0, height: 0, scale: 0.95 }}
            animate={{ opacity: 1, height: "auto", scale: 1 }}
            transition={{ duration: 0.6, type: "spring", bounce: 0.4 }}
          >
            <Card id="report-container" className="bg-white text-black border-zinc-200 print:shadow-none print:border-none print:bg-transparent overflow-hidden shadow-2xl">
              <CardHeader className="pdf-section border-b border-zinc-200 bg-zinc-50/80 print:bg-transparent flex flex-row justify-between items-center py-6">
                <div>
                  <CardTitle className="text-3xl font-serif text-zinc-900 flex items-center gap-3">
                    <ShieldAlert className="w-8 h-8 text-red-600" />
                    Official Ethical Audit Report
                  </CardTitle>
                  <CardDescription className="text-zinc-500 mt-2 text-sm font-serif">
                    Generated by AuraGovernance GraphRAG Engine
                  </CardDescription>
                </div>
                <div id="report-actions" className="flex gap-2 print:hidden">
                  <Button onClick={handleDownload} className="bg-blue-600 text-white hover:bg-blue-700 font-bold shadow-[0_0_15px_rgba(37,99,235,0.4)] transition-all transform hover:scale-105">
                    <Download className="w-5 h-5 mr-2" />
                    Download PDF
                  </Button>
                </div>
              </CardHeader>

              <CardContent className="p-10 print:p-0 space-y-8">
                {/* Anti-Hallucination Disclaimer */}
                <div className="bg-emerald-50 border border-emerald-200 rounded-lg p-6 flex items-start gap-4">
                  <div className="bg-emerald-100 p-2 rounded-full shrink-0">
                    <CheckCircle className="w-6 h-6 text-emerald-600" />
                  </div>
                  <div>
                    <h3 className="text-emerald-800 font-bold text-lg m-0">Zero-Hallucination Guarantee</h3>
                    <p className="text-emerald-700 text-sm mt-2 mb-0 leading-relaxed font-serif">
                      This report is deterministically anchored in our Neo4j Legal &amp; Ethical Ontology. All citations regarding the EU AI Act, GDPR, KVKK, and ethical principles are retrieved strictly via GraphRAG. The AI reasoning engine cannot hallucinate external laws or risks that are not topologically mapped in our knowledge graph.
                    </p>
                  </div>
                </div>

                <div className="prose prose-zinc prose-lg max-w-none font-serif">
                  {renderReportContent()}
                </div>

                {/* Footer for print */}
                <div className="hidden print:block mt-20 pt-8 border-t border-zinc-300 text-center text-sm text-zinc-500 font-serif">
                  AuraGovernance - Official Generated Record - {new Date().toLocaleDateString()}
                </div>
              </CardContent>
            </Card>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
}

export default function ReportPage() {
  return (
    <div className="relative min-h-screen py-10 px-4 print:py-0 print:bg-white print:text-black">
      <div className="print:hidden">
        <AnimatedBackground />
      </div>
      <Suspense fallback={<div className="text-zinc-400 text-center mt-20">Loading report interface...</div>}>
        <ReportContent />
      </Suspense>
    </div>
  );
}
