"use client";

import { useState, Suspense } from "react";
import { AnimatedBackground } from "@/components/AnimatedBackground";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { FileText, Printer, ShieldAlert, Cpu, Download } from "lucide-react";
import { toast } from "sonner";
import api from "@/services/api";
import { useSearchParams } from "next/navigation";

function ReportContent() {
  const searchParams = useSearchParams();
  const initialText = searchParams.get("text") || "";
  
  const [text, setText] = useState(initialText);
  const [loading, setLoading] = useState(false);
  const [reportData, setReportData] = useState<any>(null);

  const handleGenerateReport = async () => {
    if (!text.trim()) {
      toast.error("Please provide text to generate a report.");
      return;
    }
    setLoading(true);
    try {
      const response = await api.post("/report", { system_name: "Audit Target", text });
      
      if (response.data && response.data.report) {
        setReportData(response.data.report);
      } else {
        setReportData(response.data);
      }
      toast.success("Report generated.");
    } catch (error) {
      console.error(error);
      toast.error("Failed to generate report.");
    } finally {
      setLoading(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  const renderReportContent = () => {
    if (!reportData) return null;

    if (typeof reportData === "string") {
      return <div className="whitespace-pre-wrap">{reportData}</div>;
    }

    // If it's a structured object
    return (
      <div className="space-y-8">
        {Object.entries(reportData).map(([key, value]) => (
          <section key={key}>
            <h2 className="text-xl font-bold capitalize mb-3 text-zinc-900 border-b pb-2">
              {key.replace(/_/g, " ")}
            </h2>
            <div className="whitespace-pre-wrap text-zinc-700">
              {typeof value === "string" ? value : JSON.stringify(value, null, 2)}
            </div>
          </section>
        ))}
      </div>
    );
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6 print:m-0 print:p-0">
      {/* Configuration Section - hidden during print */}
      <Card className="bg-black/50 backdrop-blur-xl border-white/10 print:hidden">
        <CardHeader>
          <CardTitle className="text-2xl flex items-center gap-2">
            <FileText className="w-6 h-6 text-blue-400" />
            AI Ethics Audit Report Generator
          </CardTitle>
          <CardDescription className="text-zinc-400">
            Generate a comprehensive GraphRAG-powered audit report.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <Textarea
            placeholder="Describe the system..."
            className="min-h-[100px] bg-white/5 border-white/10 text-white placeholder:text-zinc-600 focus-visible:ring-blue-500/50"
            value={text}
            onChange={(e) => setText(e.target.value)}
          />
          <Button 
            onClick={handleGenerateReport} 
            disabled={loading}
            className="bg-blue-600 hover:bg-blue-700 shadow-[0_0_15px_rgba(37,99,235,0.4)] transition-all"
          >
            {loading ? "Generating Report..." : "Generate Official Report"}
          </Button>
        </CardContent>
      </Card>

      {/* Generated Report View */}
      {reportData && (
        <Card className="bg-white text-black border-zinc-200 print:shadow-none print:border-none print:bg-transparent overflow-hidden">
          <CardHeader className="border-b border-zinc-200 bg-zinc-50 print:bg-transparent flex flex-row justify-between items-center">
            <div>
              <CardTitle className="text-2xl font-serif text-zinc-900 flex items-center gap-2">
                <ShieldAlert className="w-6 h-6 text-zinc-800" />
                Ethical Audit Report
              </CardTitle>
              <CardDescription className="text-zinc-500 mt-1">Generated by AuraGovernance GraphRAG</CardDescription>
            </div>
            <div className="flex gap-2 print:hidden">
              <Button variant="outline" size="sm" onClick={handlePrint} className="border-zinc-300 text-zinc-700 hover:bg-zinc-100">
                <Printer className="w-4 h-4 mr-2" />
                Print / PDF
              </Button>
            </div>
          </CardHeader>
          <CardContent className="p-8 print:p-0">
            <div className="prose prose-zinc max-w-none font-serif">
              {renderReportContent()}
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}

export default function ReportPage() {
  return (
    <div className="relative min-h-screen py-10 px-4 print:py-0 print:bg-white print:text-black">
      <div className="print:hidden">
        <AnimatedBackground />
      </div>
      <Suspense fallback={<div>Loading report interface...</div>}>
        <ReportContent />
      </Suspense>
    </div>
  );
}
